/* ============================================
   CSTEP Attendance Scanner — script.js
   ============================================ */


// ---------------------------------------------------------------------------
// CONFIGURATION
// ---------------------------------------------------------------------------

// The n8n webhook URL that receives attendance check-in data.
// Update this if your n8n domain or webhook path ever changes.
const WEBHOOK_URL = "https://cstep-n8n.york.cuny.edu/webhook/cstep-attendance-checkin";

// Static JSON generated by GitHub Actions from Eventbrite.
const EVENTS_TODAY_URL = "events-today.json";

// The timezone used by the GitHub Action when generating today's event list.
const LOCAL_TIME_ZONE = "America/New_York";

// How long (in milliseconds) to pause scanning after each scan.
// 3000 = 3 seconds. This prevents the same QR from being sent twice.
const SCAN_COOLDOWN_MS = 3000;


// ---------------------------------------------------------------------------
// STATE — internal variables, do not edit
// ---------------------------------------------------------------------------
let html5QrCode   = null;  // holds the scanner instance
let isCoolingDown = false; // true while waiting between scans
let cooldownTimer = null;  // reference to the cooldown timeout
let todayEvents   = [];    // events loaded from events-today.json

// Set by confirmSetup() — used in every scan payload
let sessionEventId     = "";
let sessionEventName   = "";
let sessionAgendaTitle = "";


// ---------------------------------------------------------------------------
// DOM HELPER
// Shortcut for document.getElementById() — used throughout the code.
// ---------------------------------------------------------------------------
const $ = (id) => document.getElementById(id);


// ---------------------------------------------------------------------------
// STARTUP
// ---------------------------------------------------------------------------
loadEventsToday();


// ---------------------------------------------------------------------------
// TEST MODE
// When test mode is ON, the page scans real QR codes but does NOT send
// anything to n8n. Instead it displays what would have been sent.
// ---------------------------------------------------------------------------
function isTestMode() {
  return $("testModeToggle").checked;
}

function onTestModeToggle() {
  const indicator = $("testModeIndicator");
  if (isTestMode()) {
    indicator.classList.remove("hidden");
  } else {
    indicator.classList.add("hidden");
  }
}


// ---------------------------------------------------------------------------
// STATUS MESSAGE
// Shows a colored message bar below the scanner.
// type can be: "success" (green), "warning" (yellow), "error" (red), "info" (blue)
// ---------------------------------------------------------------------------
function showStatus(message, type) {
  const area = $("statusArea");
  const msg  = $("statusMessage");
  msg.textContent = message;
  msg.className   = `status-message ${type}`;
  area.classList.remove("hidden");
}

function hideStatus() {
  $("statusArea").classList.add("hidden");
}

function showSetupError(message) {
  $("setupError").textContent = message;
  $("setupError").classList.remove("hidden");
}

function hideSetupError() {
  $("setupError").classList.add("hidden");
  $("setupError").textContent = "";
}


// ---------------------------------------------------------------------------
// EVENTBRITE EVENTS
// Reads the static JSON file generated by GitHub Actions. The browser never
// receives the Eventbrite API token.
// ---------------------------------------------------------------------------
function getLocalDateString(date = new Date()) {
  const parts = new Intl.DateTimeFormat("en-US", {
    timeZone: LOCAL_TIME_ZONE,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).formatToParts(date);

  const values = Object.fromEntries(parts.map((part) => [part.type, part.value]));
  return `${values.year}-${values.month}-${values.day}`;
}

function setEventSelectOptions(events) {
  const select = $("eventSelect");
  select.textContent = "";

  const placeholder = document.createElement("option");
  placeholder.value = "";
  placeholder.textContent = "— Select today's event —";
  select.appendChild(placeholder);

  events.forEach((event) => {
    const option = document.createElement("option");
    option.value = event.id;
    option.textContent = event.starts_at
      ? `${formatEventTime(event.starts_at)} — ${event.name}`
      : event.name;
    select.appendChild(option);
  });

  select.disabled = events.length === 0;

  // Reset the session dropdown whenever the event list is rebuilt.
  setSessionOptions(null);
}

// Populate the session dropdown from the selected event's agenda.
// agenda === null  -> no event chosen yet
// agenda === []    -> event chosen but it has no agenda sessions
function setSessionOptions(agenda) {
  const select = $("sessionSelect");
  const status = $("sessionStatus");
  select.textContent = "";
  status.textContent = "";

  if (agenda === null) {
    select.appendChild(makeOption("", "— Select an event first —"));
    select.disabled = true;
    return;
  }

  if (agenda.length === 0) {
    select.appendChild(makeOption("", "— No agenda sessions for this event —"));
    select.disabled = true;
    status.textContent = "This event has no agenda sessions in Eventbrite.";
    return;
  }

  select.appendChild(makeOption("", "— Select a session —"));
  agenda.forEach((session) => {
    const label = session.start_time
      ? `${formatAgendaTime(session.start_time)} — ${session.title}`
      : session.title;
    select.appendChild(makeOption(session.title, label));
  });
  select.disabled = false;
}

function makeOption(value, text) {
  const option = document.createElement("option");
  option.value = value;
  option.textContent = text;
  return option;
}

// Called when the coordinator picks a different event.
function onEventChange() {
  hideSetupError();
  const event = todayEvents.find((item) => item.id === $("eventSelect").value);
  setSessionOptions(event ? event.agenda : null);
}

// Agenda times come from Eventbrite as a 24-hour "HH:MM" clock string.
function formatAgendaTime(hhmm) {
  const match = /^(\d{1,2}):(\d{2})$/.exec(hhmm || "");
  if (!match) return hhmm || "";
  let hour = parseInt(match[1], 10);
  const minutes = match[2];
  const period = hour >= 12 ? "PM" : "AM";
  hour = hour % 12 || 12;
  return `${hour}:${minutes} ${period}`;
}

function setEventStatus(message, type) {
  const status = $("eventListStatus");
  status.textContent = message;
  status.className = `form-help ${type || ""}`.trim();
}

function formatEventTime(isoString) {
  try {
    return new Intl.DateTimeFormat("en-US", {
      timeZone: LOCAL_TIME_ZONE,
      hour: "numeric",
      minute: "2-digit",
    }).format(new Date(isoString));
  } catch (_) {
    return "";
  }
}

async function loadEventsToday() {
  const select = $("eventSelect");
  const refreshButton = document.querySelector(".btn-small");
  const today = getLocalDateString();

  todayEvents = [];
  select.disabled = true;
  select.textContent = "";
  const loadingOption = document.createElement("option");
  loadingOption.value = "";
  loadingOption.textContent = "Loading today's events...";
  select.appendChild(loadingOption);
  setEventStatus("Loading today's Eventbrite events...", "");
  hideSetupError();

  if (refreshButton) refreshButton.disabled = true;

  try {
    const response = await fetch(`${EVENTS_TODAY_URL}?v=${Date.now()}`, {
      cache: "no-store",
    });

    if (!response.ok) {
      throw new Error(`Could not load ${EVENTS_TODAY_URL}.`);
    }

    const data = await response.json();
    const events = Array.isArray(data.events) ? data.events : [];

    if (data.date !== today) {
      throw new Error(`The event list is for ${data.date || "an unknown date"}, not ${today}.`);
    }

    todayEvents = events
      .filter((event) => event && event.id && event.name)
      .map((event) => ({
        id: String(event.id),
        name: String(event.name),
        starts_at: event.starts_at ? String(event.starts_at) : "",
        agenda: (Array.isArray(event.agenda) ? event.agenda : [])
          .filter((session) => session && session.title)
          .map((session) => ({
            title: String(session.title),
            start_time: session.start_time ? String(session.start_time) : "",
          })),
      }));

    if (todayEvents.length === 0) {
      throw new Error("No Eventbrite events are available for today.");
    }

    setEventSelectOptions(todayEvents);
    setEventStatus(
      `Loaded ${todayEvents.length} event${todayEvents.length === 1 ? "" : "s"} for ${today}.`,
      "success"
    );
  } catch (err) {
    todayEvents = [];
    setEventSelectOptions([]);
    setEventStatus(err.message || "Could not load today's events.", "error");
  } finally {
    if (refreshButton) refreshButton.disabled = false;
  }
}


// ---------------------------------------------------------------------------
// LAST SCAN DETAILS
// Displays a summary of the most recent scan at the bottom of the page.
// ---------------------------------------------------------------------------
function showLastScan({ studentName, token, eventName, sessionTitle, timestamp }) {
  const details = $("lastScanDetails");
  details.textContent = "";

  addDetailRow(details, "Student:", studentName || "—");
  addDetailRow(details, "Token:", token);
  addDetailRow(details, "Event:", eventName);
  addDetailRow(details, "Session:", sessionTitle);
  addDetailRow(details, "Time:", new Date(timestamp).toLocaleTimeString());

  $("lastScan").classList.remove("hidden");
}

function addDetailRow(parent, label, value) {
  const row = document.createElement("div");
  row.className = "detail-row";

  const labelEl = document.createElement("span");
  labelEl.className = "detail-label";
  labelEl.textContent = label;

  const valueEl = document.createElement("span");
  valueEl.textContent = value || "—";

  row.append(labelEl, valueEl);
  parent.appendChild(row);
}


// ---------------------------------------------------------------------------
// TOKEN EXTRACTION
// QR codes may contain a full URL or just a plain token string.
// ---------------------------------------------------------------------------
function extractToken(scannedText) {
  scannedText = scannedText.trim();
  try {
    const url   = new URL(scannedText);
    const token = url.searchParams.get("token");
    if (token) return token;
  } catch (_) {
    // Not a valid URL — treat the whole string as the token
  }
  return scannedText;
}


// ---------------------------------------------------------------------------
// SETUP — confirm event details before scanning begins
// ---------------------------------------------------------------------------
function confirmSetup() {
  const eventSelect   = $("eventSelect");
  const sessionSelect = $("sessionSelect");
  const selectedEvent = todayEvents.find((event) => event.id === eventSelect.value);

  hideSetupError();

  if (todayEvents.length === 0 || eventSelect.disabled) {
    showSetupError("Please load today's Eventbrite events before scanning.");
    return;
  }

  if (!selectedEvent) {
    showSetupError("Please select today's Eventbrite event.");
    eventSelect.focus();
    return;
  }

  const session = (selectedEvent.agenda || []).find((item) => item.title === sessionSelect.value);

  if (!session) {
    showSetupError("Please select a session from the agenda.");
    sessionSelect.focus();
    return;
  }

  // Store for use in every scan
  sessionEventId     = selectedEvent.id;
  sessionEventName   = selectedEvent.name;
  sessionAgendaTitle = session.title;

  // Update session summary display
  $("summaryEvent").textContent   = selectedEvent.name;
  $("summarySession").textContent = session.title;

  // Switch panels
  $("setupPanel").classList.add("hidden");
  $("scannerPanel").classList.remove("hidden");
}

// Allow admin to go back and change details (stops scanner first)
function resetSetup() {
  stopScanner();
  $("scannerPanel").classList.add("hidden");
  $("setupPanel").classList.remove("hidden");
  hideStatus();
  $("lastScan").classList.add("hidden");
}


// ---------------------------------------------------------------------------
// SCANNER — START
// Initialises the html5-qrcode library and opens the camera.
// ---------------------------------------------------------------------------
async function startScanner() {
  hideStatus();
  $("scannerWrapper").classList.remove("hidden");
  $("startBtn").disabled = true;
  $("stopBtn").disabled  = false;

  // Create the scanner instance the first time
  if (!html5QrCode) {
    html5QrCode = new Html5Qrcode("qr-reader");
  }

  // Scanner settings
  const config = {
    fps: 10,                          // frames per second to check for QR codes
    qrbox: { width: 250, height: 250 }, // the green scanning box size
    aspectRatio: 1.0,
    rememberLastUsedCamera: true,
  };

  html5QrCode
    .start(
      { facingMode: "environment" }, // use the rear camera on mobile
      config,
      onScanSuccess,  // called when a QR code is detected
      onScanFailure   // called every frame when no QR is found (normal)
    )
    .catch((err) => {
      showStatus("Camera error: " + err, "error");
      resetScannerUI();
    });
}


// ---------------------------------------------------------------------------
// SCANNER — STOP
// Stops the camera and resets the UI.
// ---------------------------------------------------------------------------
function stopScanner() {
  if (html5QrCode && html5QrCode.isScanning) {
    html5QrCode
      .stop()
      .then(() => resetScannerUI())
      .catch((err) => {
        console.warn("Stop error:", err);
        resetScannerUI();
      });
  } else {
    resetScannerUI();
  }
}

function resetScannerUI() {
  $("scannerWrapper").classList.add("hidden");
  $("startBtn").disabled = false;
  $("stopBtn").disabled  = true;
  if (cooldownTimer) clearTimeout(cooldownTimer);
  isCoolingDown = false;
}


// ---------------------------------------------------------------------------
// ON SCAN SUCCESS
// Called automatically by html5-qrcode when a QR code is detected.
// ---------------------------------------------------------------------------
function onScanSuccess(decodedText) {
  // Ignore scans during the cooldown window (prevents duplicate submissions)
  if (isCoolingDown) return;

  // Immediately pause the scanner so the same code isn't sent twice.
  isCoolingDown = true;
  if (html5QrCode) {
    try { html5QrCode.pause(false); } catch (_) {}
  }

  const token     = extractToken(decodedText);
  const timestamp = new Date().toISOString();

  showStatus(isTestMode() ? "Preparing test scan..." : "Sending check-in data...", "info");

  // Keep this payload intentionally small for the n8n workflow.
  const payload = {
    qr_token:     token,
    event_id:     sessionEventId,
    event_name:   sessionEventName,
    agenda_title: sessionAgendaTitle,
  };

  sendCheckin(payload, timestamp);
}

// Called every frame when no QR code is visible — this is normal behaviour.
// We suppress the most common noisy message to keep the console clean.
function onScanFailure(error) {
  if (!error.includes("No MultiFormat Readers")) {
    console.debug("QR scan frame:", error);
  }
}


// ---------------------------------------------------------------------------
// SEND TO N8N WEBHOOK (or simulate if test mode is on)
// ---------------------------------------------------------------------------
async function sendCheckin(payload, timestamp) {
  try {
    let data;

    if (isTestMode()) {
      showStatus(`Scanned token: ${payload.qr_token}`, "info");
      showLastScan({
        studentName: "(test mode — not sent to n8n)",
        token: payload.qr_token,
        eventName: payload.event_name,
        sessionTitle: payload.agenda_title,
        timestamp,
      });
      resumeAfterCooldown();
      return;
    }

    const response = await fetch(WEBHOOK_URL, {
      method:  "POST",
      headers: { "Content-Type": "application/json" },
      body:    JSON.stringify(payload),
    });

      // Try to parse the JSON response from n8n
      try {
        data = await response.json();
      } catch (_) {
        // n8n returned something that isn't valid JSON
        data = { status: "error", message: "Unexpected response from server." };
      }

    if (!response.ok && data.status !== "duplicate") {
      data.status = "error";
      data.message = data.message || "Server returned an error.";
    }

    handleWebhookResponse(data, payload, timestamp);
  } catch (networkErr) {
    showStatus("Network error: Could not reach the server. Check your connection.", "error");
    resumeAfterCooldown();
  }
}


// ---------------------------------------------------------------------------
// HANDLE N8N RESPONSE
// n8n returns a JSON object with a "status" field.
// ---------------------------------------------------------------------------
function handleWebhookResponse(data, payload, timestamp) {
  const studentName = data.student_name || "";

  if (data.status === "success") {
    showStatus(
      `Checked in${studentName ? ": " + studentName : ""}` +
      (data.message ? " — " + data.message : ""),
      "success"
    );
    showLastScan({
      studentName,
      token: payload.qr_token,
      eventName: payload.event_name,
      sessionTitle: payload.agenda_title,
      timestamp,
    });
  } else if (data.status === "duplicate") {
    showStatus(
      `Already checked in${studentName ? ": " + studentName : ""}` +
      (data.message ? " — " + data.message : ""),
      "warning"
    );
    showLastScan({
      studentName,
      token: payload.qr_token,
      eventName: payload.event_name,
      sessionTitle: payload.agenda_title,
      timestamp,
    });
  } else {
    showStatus(`Error: ${data.message || "Unknown error. Please try again."}`, "error");
  }

  // Resume scanning after the cooldown period
  resumeAfterCooldown();
}


// ---------------------------------------------------------------------------
// COOLDOWN RESUME
// Waits SCAN_COOLDOWN_MS milliseconds, then re-activates the scanner.
// ---------------------------------------------------------------------------
function resumeAfterCooldown() {
  cooldownTimer = setTimeout(() => {
    isCoolingDown = false;
    if (html5QrCode) {
      try { html5QrCode.resume(); } catch (_) {}
    }
  }, SCAN_COOLDOWN_MS);
}
